<?php

/**
 * @file
 * Contains eldrich.module.
 */


use Drupal\Core\Database\Database;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Node\Entity\Node;

function eldrich_entity_update(EntityInterface $entity) {
  if (in_array($entity->bundle(), ['campaign', 'gear_type'])) {
    \Drupal::service("router.builder")->rebuild();
  }
}

function eldrich_entity_insert(EntityInterface $entity) {
  if (in_array($entity->bundle(), ['campaign', 'gear_type'])) {
    \Drupal::service("router.builder")->rebuild();
  }
}

function eldrich_entity_presave(EntityInterface $entity) {
  // when Weapon Instances and Armor Instances are saved, title them.
  // Weapon Pattern: Short Weapon Name (Mod Shortnames) with [Smart Ammo features] Ammo Name

  if (($entity->getEntityType()->id() == 'instance')) {
    switch ($entity->bundle()) {
      case 'weapon_instance':
        $entity->title = $entity->field_weapon->entity->label();
        break;
      case 'armor_instance':
        $entity->title = $entity->field_armor->entity->label();
        break;
      case 'morph':
        // If the morph isn't populated, copy over the data from its template model.
        if (!$entity->field_model->isEmpty()) {
          $entity->title = $entity->field_model->entity->label();
          if ($entity->field_stats->isEmpty()) {
            $entity->field_stats = $entity->field_model->entity->field_stats->getValue();
          }

          // …But always copy over the Synthetic flag.
          $entity->field_stats->synthetic = $entity->field_model->entity->field_stats->synthetic;

          if ($entity->field_traits->isEmpty()) {
            $entity->field_traits = $entity->field_model->entity->field_traits->getValue();
          }
          if ($entity->field_mobility_system->isEmpty()) {
            $entity->field_mobility_system = $entity->field_model->entity->field_mobility_system->getValue();
          }
          if ($entity->field_movement_speed->isEmpty()) {
            $entity->field_movement_speed = $entity->field_model->entity->field_movement_speed->getValue();
          }
          if ($entity->field_augmentations->isEmpty()) {
            $entity->field_augmentations = $entity->field_model->entity->field_augmentations->getValue();
          }
          if ($entity->field_skills->isEmpty()) {
            $entity->field_skills = $entity->field_model->entity->field_skills->getValue();
          }
        }
        break;
      case 'muse':
        // If the muse doesn't have any data, pre-populate it as a Standard Muse
        break;
    }
  }

  // This is terrible and a sign that I've failed as a human
  if (($entity->getEntityType()->id() == 'node') && $entity->bundle() == 'creature') {
    if (!$entity->field_creature_type->isEmpty()) {
      $ct = $entity->field_creature_type->entity->label();
      if ($ct = 'Smart Animal') {
        $entity->field_gear_type->target_id = 30;
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function eldrich_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // If this is a subsequent step of a multi-step form, the prepopulate values
  // have done their work, and the user may have modified them: bail.
  if (!empty($form_state->rebuild_info)) {
    return;
  }
  if (isset($_REQUEST['source']) || isset($_REQUEST['campaign'])) {
    $form['#after_build'][] = 'eldrich_prepopulator_after_build';
  }
}

/**
 * If someone creates content with an 'Add an X' button, prepopulate the campaign
 * or source field and disable it so it can't be monkeyed with.
 */
function eldrich_prepopulator_after_build($form) {
  if (isset($_REQUEST['source'])) {
    $source_id = (int) $_REQUEST['source'];
    if ($node = Node::load($source_id)) {
      if (in_array($node->bundle(), ['campaign', 'inspiration'])) {
        if (isset($form['field_sources'])) {
          $form['field_sources']['widget'][0]['target_id']['#value'] = $node->id();
          $form['field_sources']['widget'][0]['target_id']['#default_value'] = $node->id();
          $form['field_sources']['widget'][0]['target_id']['#attributes']['disabled'] = TRUE;
          $form['field_sources']['widget'][0]['quantity']['#attributes']['disabled'] = TRUE;
          $form['field_sources']['widget']['add_more']['#attributes']['disabled'] = TRUE;
        }
      }
    }
  }
  if (isset($_REQUEST['campaign'])) {
    $campaign_id = (int) $_REQUEST['campaign'];
    if ($node = Node::load($campaign_id)) {
      if ($node->bundle() == 'campaign') {
        if (isset($form['field_campaign'])) {
          $form['field_campaign']['widget']['#value'] = $node->id();
          $form['field_campaign']['widget']['#default_value'] = $node->id();
          $form['field_campaign']['widget']['#attributes']['disabled'] = TRUE;
        }
      }
    }
  }
  return $form;
}

function eldrich_delete_orphaned_ecks() {
  $fields = [
    'field_muse',
    'field_morph',
    'field_status',
    'field_identity',
    'field_equipped_armor',
    'field_equipped_weapons',
    'field_native_abilities',
    'field_native_attacks'
  ];
  $eck_types = ['component', 'instance'];
}
