<?php

/**
 * @file
 * Contains eldrich_utils.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function eldrich_utils_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the eldrich_utils module.
    case 'help.page.eldrich_utils':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Formatting and data mangement helpers for Eldrich Host') . '</p>';
      return $output;

    default:
  }
}


function eldrich_utils_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {

}
