<?php

/**
 * @file
 * Contains ep_import.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\migrate\Row;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;

/**
 * Implements hook_help().
 */
function ep_import_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ep_import module.
    case 'help.page.ep_import':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Imports data tables and other miscellanea for an Eclipse Phase site.') . '</p>';
      return $output;

    default:
  }
}

function ep_import_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
//  drush_print_r($row);
}


function ep_import_purge_ecks() {
  // list of types and the fields they're linked from
  $targets = [
    'component' => [],
    'instance' => [],
  ];

  $ids = [];

  $controller = \Drupal::entityManager()->getStorage($entity_type);
  $entities = $controller->loadMultiple($ids);
  $controller->delete($entities);
}


function ep_import_date($value) {
  $date = DateTime::createFromFormat('m/d/y H:i a', $value);
  if ($date) {
    return $date->getTimestamp();
  }
  return time();
}
