<?php

/**
 * @file
 * Contains operation.module..
 */

function operation_parse_string($string) {
  $string = str_replace(' ', '', $string);
  $string = str_replace(',', '', $string);
  $matches = [];
  return preg_match("/(?<operator>[+-\/\*\^%=])(?<value>[0-9]+)/", $string, $matches);
}


function operation_calculate_result($input, $operation, $value, $up = TRUE) {
  switch ($operation) {
    case '+':
      $value = $input + $value;
      break;
    case '-':
      $value = $input - $value;
      break;
    case '/':
      $value = $input / $value;
      break;
    case '*':
      $value = $input * $value;
      break;
    case '^':
      $value = $input ** $value;
      break;
    case '%':
      $value = $input % $value;
      break;
  }

  if ($up) {
    return ceil($value);
  }
  else {
    return floor($value);
  }
}

function operation_supported_operators() {
  return [
    '+' => t('Addition'),
    '-' => t('Subtraction'),
    '/' => t('Division'),
    '*' => t('Multiplication'),
    '^' => t('Exponentiation'),
    '%' => t('Modulo'),
    '=' => t('Override'),
  ];
}