<?php

/**
 * @file
 * Contains ep_date.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ep_date_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ep_date module.
    case 'help.page.ep_date':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Eclipse Phase') . '</p>';
      return $output;

    default:
  }
}
