<?php

/**
 * @file
 * Contains newshub_utils.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function newshub_utils_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the newshub_utils module.
    case 'help.page.newshub_utils':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Filters, alter hooks, and custom formatters for NYU Langone Newshub') . '</p>';
      return $output;

    default:
  }
}
