<?php

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;


/**
 * @file
 * Contains saved_query.module.
 */

/**
 * Returns a list of defined saved_query_field fields.
 * @return array
 */
function saved_query_candidate_fields() {
  $candidate_fields = [];

  $field_map = \Drupal::entityManager()->getFieldMap();
  foreach ($field_map as $entity_type_id => $field) {
    foreach ($field as $field_name => $info) {
      if ($info['type'] == 'saved_query_field') {
        $candidate_fields[$entity_type_id][] = $field_name;
      }
    }
  }

  return $candidate_fields;
}

/**
 * Finds a list of entities with saved_query_fields scheduled for refresh.
 * @param int $limit
 * @return array
 */
function saved_query_find_candidates($limit) {
  $results = [];
  $fields = saved_query_candidate_fields();
  foreach ($fields as $entity_type => $field_names) {
    foreach ($field_names as $field_name) {
      $query = \Drupal::entityQuery($entity_type);
      $now = time();

      // TODO: Use a select query and subtract interval from $now, filtering out already-refreshed entities.
      $query
        ->condition("$field_name.interval", 0, '>')
        ->condition('status', 1);

      if ($limit) {
        $query->range(0, $limit);
      }
      if ($ids = $query->execute()) {
        $results[$entity_type][$field_name] = $ids;
      }
    }
  }
  return $results;
}


/**
 * Given an entity type, field, and a set of IDs, run the reference updater
 * for each entity.
 *
 * @param string $entity_type
 * @param string $field
 * @param array $ids
 */
function saved_query_update_references($entity_type, $field, $ids) {
  $manager = \Drupal::entityManager()->getStorage($entity_type);
  $entities = $manager->loadMultiple($ids);
  foreach ($entities as $entity) {
    saved_query_update_single_entity($entity, $field);
  }
}

/**
 * Do the actual work of loading a query from the saved_query_field, running it,
 * and updating the destination entity_reference field with the results.
 *
 * @param \Drupal\Core\Entity\FieldableEntityInterface $entity
 * @param string $field
 */
function saved_query_update_single_entity(FieldableEntityInterface $entity, $field) {
  $query_field = $entity->get($field)[0];
  $target_field = $entity->getFieldDefinition($field)->getSetting('target_field');

  if ($query = $query_field->getQuery()) {
    $matches = $query->execute();
    $reference_data = [];
    foreach ($matches as $id => $match) {
      $reference_data[] = ['target_id' => $id];
    }
    if ($reference_data) {
      // TODO: Preserve existing values, if entities are already referenced.
      $entity->set($target_field, $reference_data);
      $entity->save();
    }
  }
}
