<?php

/**
 * @file
 * Contains saved_query.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function saved_query_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the saved_query module.
    case 'help.page.saved_query':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides an entity to save EntityQuery conditions and properties.') . '</p>';
      return $output;

    default:
  }
}
